### ISSUE TITLE
Hi, how do I configure the assembly.asm

### ISSUE THREAD

**Issue by YMY1666527646** [ryan-weil/ReadWriteDriver#1]
seriousness 	 code 	 explain 	 project 	 file 	 that 's ok 	 Disable display status
error 	 MSB3721 	 The command "ml64.exe / C / nologo / Zi / fo" x64 \ release \ assembly. Obj "/ W3 / errorreport: prompt / Ta.. \ x64 \ debug \ assembly. ASM" exited with a return code of 1. 	 ReadWriteDriver 	 C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm. targets 	 seventy 	
error 	 A1000 	 cannot open file : .. \x64\Debug\assembly. asm 	 ReadWriteDriver 	 E:\ReadWriteDriver-master\ReadWriteDriver-master\ReadWriteDriver\MASM 	 one
![20220117003634](https://user-images.githubusercontent.com/84628110/149668988-89f95f8f-b86c-4d16-96de-9d232cf9162a.png)

Hi, how do I configure the assembly asm
I can't find rel
![20220117004806](https://user-images.githubusercontent.com/84628110/149669404-b0f24482-0347-43ef-aec6-d8238921625c.png)
evant information on the Internet

**Comment by ryan-weil** [comment]
Git did not include assembly.asm when I created the repo for some reason. I have pushed it now, so if you pull or redownload the project it should be fine now :)

**Comment by YMY1666527646** [comment]
> Git did not include assembly.asm when I created the repo for some reason. I have pushed it now, so if you pull or redownload the project it should be fine now :)

Thank you very much for your help and guidance

**Comment by YMY1666527646** [comment]
Can it only be used for windows 11? I installed the driver blue screen on window 10 1909

**Comment by ryan-weil** [comment]
Read the README

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ryan-weil** [comment]
> Can it only be used for windows 11? I installed the driver blue screen on window 10 1909

Read the README file. It specifically says that I hard-coded the addresses for a specific Windows 11 version.

I or someone else will eventually have to write a sig scanner to fix this.

In the meantime, you open ntoskrnl and win32kbase in IDA and just get 3 function addresses and paste them in. Ezpz

**Comment by YMY1666527646** [comment]
> > Can it only be used for windows 11? I installed the driver blue screen on window 10 1909
> 
> Read the README file. It specifically says that I hard-coded the addresses for a specific Windows 11 version.
> 
> I or someone else will eventually have to write a sig scanner to fix this.
> 
> In the meantime, you open ntoskrnl and win32kbase in IDA and just get 3 function addresses and paste them in. Ezpz

Well, thank you very much.
